client_join_message:
  enabled: true
  value: |-
    §r
    §r
    §6▏ 
    §6▏ Welcome to §nExampleGen§6!
    §6▏ 
    §6▏ §e🔗 Discord: §nhttps://discord.gg/xyz
    §6▏ §e🔗 Youtube: §nhttps://youtube.com/@xyz
    §6▏ 
    §6▏ We hope you will have a great time!
    §6▏ §o(mc.example.com)
    §6▏ 

client_join_sound:
  enabled: false
  sound: item.honey_bottle.drink
  volume: 1
  pitch: 1.3

join_message:
  custom: true
  value: |-
    §a[ + ]§2 %player%§7 joined

quit_message:
  custom: true
  value: |-
    §c[ - ]§4 %player%§7 quit
