name: GenCore
description: $description
version: '${version}'

main: universal66.gencore.GenCore
api-version: '26.1'
load: STARTUP

authors: [ Universal66 ]

commands:
  spawn:
    usage: /spawn
    aliases: [spawntp, tpspawn]
    permission: gencore.spawn
    permission-message: "§7[§6SetSpawn§7] §cError: §4No permission"
    description: Teleports you to spawn.
  setspawn:
    usage: /setspawn
    aliases: spawnset
    permission: gencore.setspawn
    permission-message: "§7[§6SetSpawn§7] §cError: §4No permission"
    description: Sets the spawn location.
  generator:
    usage: /generator <block>
    aliases: [gen, makegen, makegenerator, creategen, creategenerator, givegen, givegenerator]
    permission: gencore.generator
    permission-message: "§7[§6Generator§7] §cError: §4No permission"
    description: Gives you a block that generates a generator 2 blocks above it.
  up:
    usage: /up <height>
    aliases: [goup, tpup, teleportup]
    permission: gencore.up
    permission-message: "§7[§6Up§7] §cError: §4No permission"
    description: Teleports you an amount of blocks up.
  down:
    usage: /down <height>
    aliases: [godown, tpdown, teleportdown]
    permission: gencore.down
    permission-message: "§7[§6Down§7] §cError: §4No permission"
    description: Teleports you an amount of blocks down.
  banhammer:
    usage: /banhammer
    permission: gencore.banhammer
    permission-message: "§7[§6BanHammer§7] §cError: §4No permission"
    description: Gives you an item, that when clicked on a player, bans it from the server.
  heal:
    usage: /heal
    aliases: [regenerate]
    permission: gencore.heal
    permission-message: "§7[§6Heal§7] §cError: §4No permission"
    description: Restores your health and hunger.

permissions:
  gencore.spawn:
    default: true
  gencore.spawn.others:
    default: op
  gencore.setspawn:
    default: op
  gencore.generator:
    default: op
  gencore.up:
    default: op
  gencore.down:
    default: op
  gencore.banhammer:
    default: op
  gencore.heal:
    default: op
